### PR TITLE
Draw condensed digraphs

### PR DESCRIPTION
**Pull request by lynn**
Now there is exactly one dot per mora:

image

Compare to this example from a Japanese dictionary.

image

### CODE REVIEW

**Comment by lynn** [comment]
I replaced the `pitchPatterns` table with a formula. Now the output is correct for long (>7 mora) words:

image

**Comment by lynn** [comment]
I applied some more letter-spacing/transform tweaks to make the result a little more readable.

Before:

image

After:

image

**Comment by lynn** [comment]
Oops, there is a bug where the digraph-squishing transformation happens twice if there are two possible accents. I will fix this soon.

image

**Comment by lynn** [comment]
It's fixed.

**Comment by DJTB** [comment]
If you need more flexibility, I created a tiny lib a while back to display the pitch diagrams in Kaniwani. Might save some time for any future changes.
https://github.com/DJTB/hatsuon

**Pull request merged**
